name: water_tracking_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_auth: ^5.3.1 # ใช้สำหรับ Authentication
  firebase_ui_auth: ^1.16.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/water_bottle.png
    - assets/wave.png
    - assets/wavedialog.png